/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface HolstForPresentation {
    }
    interface MyMenu {
    }
    interface SlideMenu {
    }
    interface TextRedactor {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLHolstForPresentationElement extends Components.HolstForPresentation, HTMLStencilElement {
    }
    var HTMLHolstForPresentationElement: {
        prototype: HTMLHolstForPresentationElement;
        new (): HTMLHolstForPresentationElement;
    };
    interface HTMLMyMenuElement extends Components.MyMenu, HTMLStencilElement {
    }
    var HTMLMyMenuElement: {
        prototype: HTMLMyMenuElement;
        new (): HTMLMyMenuElement;
    };
    interface HTMLSlideMenuElement extends Components.SlideMenu, HTMLStencilElement {
    }
    var HTMLSlideMenuElement: {
        prototype: HTMLSlideMenuElement;
        new (): HTMLSlideMenuElement;
    };
    interface HTMLTextRedactorElement extends Components.TextRedactor, HTMLStencilElement {
    }
    var HTMLTextRedactorElement: {
        prototype: HTMLTextRedactorElement;
        new (): HTMLTextRedactorElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "holst-for-presentation": HTMLHolstForPresentationElement;
        "my-menu": HTMLMyMenuElement;
        "slide-menu": HTMLSlideMenuElement;
        "text-redactor": HTMLTextRedactorElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface HolstForPresentation {
    }
    interface MyMenu {
    }
    interface SlideMenu {
    }
    interface TextRedactor {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "holst-for-presentation": HolstForPresentation;
        "my-menu": MyMenu;
        "slide-menu": SlideMenu;
        "text-redactor": TextRedactor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "holst-for-presentation": LocalJSX.HolstForPresentation & JSXBase.HTMLAttributes<HTMLHolstForPresentationElement>;
            "my-menu": LocalJSX.MyMenu & JSXBase.HTMLAttributes<HTMLMyMenuElement>;
            "slide-menu": LocalJSX.SlideMenu & JSXBase.HTMLAttributes<HTMLSlideMenuElement>;
            "text-redactor": LocalJSX.TextRedactor & JSXBase.HTMLAttributes<HTMLTextRedactorElement>;
        }
    }
}
